config/routes.rb
Rails.application.routes.draw do
 
  get 'welcome/about', to: 'welcome#about', as: :about

  resources :reviews
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :movies do
    collection do
        get 'search'
    end
    resources :reviews
  end

  match 'auth/:provider/callback', to: 'sessions#create', :via => [:get]
  match 'auth/failure', to: redirect('/'), :via => [:get]
  match 'signout', to: 'sessions#destroy', as: 'signout', :via => [:get]

  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_many :reviews
	has_many :users, through: :reviews
	has_attached_file :poster, styles: { medium: "300x400#" }
	validates_attachment_content_type :poster, content_type: /\Aimage\/.*\Z/
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :role
	has_many :reviews
	has_many :users, through: :reviews

	def self.from_omniauth(auth)
		user = User.find_by_provider_and_uid(auth.provider, auth.uid)
		if user.blank?
			user = User.new
		    user.provider = auth.provider
		    user.uid = auth.uid
		    user.name = auth.info.name
		    user.email = auth.info.email
		    user.image_path = auth.info.image
		    user.oauth_token = auth.credentials.token
		    user.role ||= Role.find_by_name('customers')
		    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
		    user.save!
		end
		return user    
	end

	def is_admin?
		self.role.name == 'admin'
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    keyword = params[:keyword]
    @movies = []
    if keyword.present?
      @movies = Movie.where("title like ?", "%#{keyword}%")
    end
    render :index, location: @movie
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find_by_id(params[:id])
      if @movie.blank?
        redirect_to root_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :duration, :director, :rating, :description, :poster)
    end

    def authorize
      if @current_user.blank?
        redirect_to root_url
      end
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment, :movie_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:piture] =
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def active_class(controller_name, action_name)    
    	"active" if current_page?(controller: controller_name, action: action_name)
  	end
  
  	def active_span(controller_name, action_name)
    	"(current)" if current_page?(controller: controller_name, action: action_name)
  	end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<style>
  .modal-header, h4, .close {
      background-color: #5cb85c;
      color:white !important;
      text-align: center;
      font-size: 30px;
  }
  .modal-footer {
      background-color: #f9f9f9;
  }
  .cursor_pointer {
    cursor: pointer;
  }
</style>
<div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Movie Reviews", root_path, class: "navbar-brand" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if current_user.present? && current_user.is_admin? %>
              <li class="nav-item <%= active_class('movies', 'new') %>">
        			  <%= link_to new_movie_path, class: "nav-link" do %>
        				New Movie
        				<span class="sr-only"> <%= active_span('movies', 'new') %> </span>
        			  <% end %>	  
      		    </li>	
			      <% end %>
    		    
            <li class="nav-item <%= active_class('welcome', 'about') %>">
    			  <%= link_to about_path, class: 'nav-link' do %>
    				About
    				<span class="sr-only"> <%= active_span('welcome', 'about') %> </span>
    			  <% end %>
    		    </li>
          </ul>

		    	<%= form_tag(search_movies_path, method: :get, class: "navbar-form navbar-left form-inline pull-xs-right", role: 'search') do %>
			    <div class="input-group">
			        <%= text_field_tag :keyword, params[:keyword], class: 'form-control', placeholder: "Search" %>
				
			        <div class="input-group-btn">
			          <button class="btn btn-default" type="submit">
			            <i class="glyphicon glyphicon-search"></i>
			          </button>
			        </div>
			      </div>
			  <% end %>	

		    <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
			      <li class="nav-item ">
              <a class="nav-link" href="#">
              <%= current_user.name %>
              <span class="sr-only">  </span>
              </a>
            </li> 
            <li class="nav-item ">
              <%= link_to "Sign out", signout_path, id: "sign_out", class: "nav-link" %>
              <span class="sr-only">  </span>
            </li>	  
          <% else %>
  			    <li>
              <a id="login" class="cursor_pointer">
                <span class="glyphicon glyphicon-log-in"></span>
                Login
              </a>
            </li>
  			  <% end %>
		    </ul>
        </div>
      </div>
    </div>



    <div class="modal fade" id="myModal" role="dialog">
      <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4>Movie Review</h4>
          </div>
          <div class="modal-body" style="padding:40px 50px;">
            <form role="form">
              <a href='/auth/facebook' class="btn btn-block btn-social btn-facebook">
                <span class="fa fa-facebook"></span> Connect with Facebook
              </a>
              <a href='/auth/google_oauth2' class="btn btn-block btn-social btn-google">
                <span class="fa fa-google"></span> Connect with Google
              </a>
            </form>
          </div>
        </div>
      </div>
    </div> 
   
  <script>
    $(document).ready(function(){
        $("#login").click(function(){
            $("#myModal").modal();
        });
    });
    </script>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieReviewApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background: #e7e7e7;">
	<%= render 'layouts/header' %>
    <div class="container">
        <% flash.each do |name, msg| %>
            <%= content_tag(:div, msg, class: "alert alert-info") %>
        <% end %>
        <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie,  html: { multipart: true, :class => "form-horizontal movie" } do |f| %>

  <% if @movie.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :poster, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :poster, :class => 'form-control' %>
    </div>
    <%=f.error_span(:poster) %>
  </div>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :duration, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :duration, :class => 'form-control' %>
    </div>
    <%=f.error_span(:duration) %>
  </div>
  <div class="form-group">
    <%= f.label :director, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :director, :class => 'form-control' %>
    </div>
    <%=f.error_span(:director) %>
  </div>
  <div class="form-group">
    <%= f.label :rating, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :rating, :class => 'form-control' %>
    </div>
    <%=f.error_span(:rating) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                movies_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/movies/edit.html.erb
<%- model_class = Movie -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/movies/index.html.erb
<div class="row">
  <% @movies.each do |movie| %>
    <div class="col-sm-6 col-md-5">
      <div class="thumbnail">
        <%= link_to (image_tag movie.poster.url(:medium), class: 'image img-thumbnail', title: movie.title), movie %>
      </div>
      <hr/>
    </div>
  <% end %>
</div>

app/views/movies/new.html.erb
<%- model_class = Movie -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/movies/show.html.erb
<%- model_class = Movie -%>
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default" style="height: 500px; background: #e7e7e7;">
      <div class="panel-heading"><%= @movie.title %></div>
        <div class="panel-body">
            <%= image_tag @movie.poster.url(:medium), class: "img-thumbnail" %>
            <br/>
            <!-- <label for="input-1" class="control-label">Rate This</label> -->
            <div id="stars" class="starrr" data-rating='<%=@movie.rating%>'></div>
            <!-- <label for="input-1" class="control-label">You gave a rating of <span id="count">0</span> star(s)</label> -->
        </div>
      </div>
  </div>
  
  <div class="col-md-6">
    <div class="panel panel-default" style="height:500px;background: #e7e7e7;">
      <div class="panel-heading"> Details</div>
        <div class="panel-body">
          <dl class="dl-horizontal">
            <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
            <dd><%= @movie.title %></dd>
            <dt><strong><%= model_class.human_attribute_name(:duration) %>:</strong></dt>
            <dd><%= @movie.duration %></dd>
            <dt><strong><%= model_class.human_attribute_name(:director) %>:</strong></dt>
            <dd><%= @movie.director %></dd>
            <dt><strong><%= model_class.human_attribute_name(:rating) %>:</strong></dt>
            <dd><%= @movie.rating %></dd>
            <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
            <dd><%= @movie.description %></dd>
          </dl>
          <% if current_user.present? && current_user.is_admin? %>
            <%= link_to t('.back', :default => t("helpers.links.back")),
                          movies_path, :class => 'btn btn-default'  %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_movie_path(@movie), :class => 'btn btn-default' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        movie_path(@movie),
                        :method => 'delete',
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-danger' %>
          <% end %>
        </div>
      </div>
  </div>
  
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $(".starrr").starrr();
    // $('#stars').on('starrr:change', function(e, value){
    //   $('#count').html(value);
    // });
    
    // $('#stars-existing').on('starrr:change', function(e, value){
    //   $('#count-existing').html(value);
    // });
  });
</script>

app/views/reviews/_form.html.erb
<%= form_for @review, :html => { :class => "form-horizontal review" } do |f| %>

  <% if @review.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :rating, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :rating, :class => 'form-control' %>
    </div>
    <%=f.error_span(:rating) %>
  </div>
  <div class="form-group">
    <%= f.label :comment, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :comment, :class => 'form-control' %>
    </div>
    <%=f.error_span(:comment) %>
  </div>
  <div class="form-group">
    <%= f.label :movie_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :movie_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:movie_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                reviews_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/reviews/edit.html.erb
<%- model_class = Review -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reviews/index.html.erb
<%- model_class = Review -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:rating) %></th>
      <th><%= model_class.human_attribute_name(:comment) %></th>
      <th><%= model_class.human_attribute_name(:movie_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= link_to review.id, review_path(review) %></td>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>
        <td><%= review.movie_id %></td>
        <td><%=l review.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      review_path(review), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_review_path(review), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      review_path(review),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_review_path,
            :class => 'btn btn-primary' %>

app/views/reviews/new.html.erb
<%- model_class = Review -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reviews/show.html.erb
<%- model_class = Review -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:rating) %>:</strong></dt>
  <dd><%= @review.rating %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comment) %>:</strong></dt>
  <dd><%= @review.comment %></dd>
  <dt><strong><%= model_class.human_attribute_name(:movie_id) %>:</strong></dt>
  <dd><%= @review.movie_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              reviews_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_review_path(@review), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              review_path(@review),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/welcome/about.html.erb
Movie review